Fix/Convert_rgb_xy colors null division
Catch cases of x+y+z == 0 in `convert_rgb_xy` function in `colors.py`

This was the request producing this problem for me:
```
2020-09-27 11:01:01,398 - root - INFO - b'{"transitiontime": 7, "hue": 0, "on": true, "bri": 10, "sat": 0}'
----------------------------------------
Exception happened during processing of request from ('192.168.178.70', 53278)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1828, in do_PUT
    sendLightRequest(url_pices[4], put_dictionary, bridge_config["lights"], bridge_config["lights_address"])
  File "/opt/hue-emulator/functions/lightRequest.py", line 162, in sendLightRequest
    xyValue = convert_rgb_xy(rgbValue[0], rgbValue[1], rgbValue[2])
  File "/opt/hue-emulator/functions/colors.py", line 24, in convert_rgb_xy
    x = X / (X + Y + Z)
ZeroDivisionError: float division by zero
```
This edge case might have been overlooked since such requests with a 0 hue seem useless but can still occur for example when using a kodi ambilight addon